### ISSUE TITLE
Escaping passwords during repo init

### ISSUE THREAD

**Issue by pefmeister** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#1]
When I create a remote repo using the webinterface, the password that is being put into BORG_PASSPHRASE is not escaped into single quotes. Thus having special characters in the password crashes the execution. This is what I get:

`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE=mypasspart1&part2 /usr/bin/borg init --encryption=keyfile 'borg@backup.example.com:/backup/myhost'' with exit code '127': `

`Fehler #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE=mypasspart1&part2 /usr/bin/borg init --encryption=keyfile 'borg@backup.example.com:/backup/myhost'' with exit code '127':  in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/borgbackup.inc(152): OMV\System\Process->execute(Array)
#1 [internal function]: OMVRpcServiceBorgBackup->setRepo(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setRepo', Array, Array)
#4 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('BorgBackup', 'setRepo', Array, Array, 1)
#5 {main}
`

If I use the same command on the CLI with the escaped password, it does work.

**Comment by ryecoaaron** [comment]
Fixed in 4.0.1 - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/d1c5f1d77adc566d764cef56153f37ff694fdda3

**Comment by pefmeister** [comment]
Thanks for the fast response, seems to work nicely!
