### ISSUE TITLE
Support passing --remote-ratelimit or custom options to borg

### ISSUE THREAD

**Issue by ebarnard** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#11]
It would be great if this plugin could support either the `--remote-ratelimit` option or support passing custom options to borg. It is very useful to be able to limit the upload bandwidth on a slow network connection.

**Comment by ryecoaaron** [comment]
It looks like --remote-ratelimit works with all borg commands.  Would you want the limit applied to all commands or a select few?

**Comment by ebarnard** [comment]
I thought it only limited upload speed, so only make a difference for `borg create`, but I might be wrong.

If it is only for upload speed it's probably best as an option on each Archive.

If it applies to everything then probably an option on the Repo makes sense.

**Comment by ryecoaaron** [comment]
Since I'm not a user, I will let you decide.

**Comment by ebarnard** [comment]
I think per archive makes the most sense. There are some archives that I want to make sure get backed up ASAP and others where it doesn't matter if it takes a while.

**Comment by ryecoaaron** [comment]
I have added this feature and committed the code.  I just need to do a bit more testing and then I will release the package.

**Comment by ebarnard** [comment]
Thank you for implementing this so quickly.

**Comment by ryecoaaron** [comment]
5.0.6 is in the repo now.
