### ISSUE TITLE
Unable to create a Repo.

### ISSUE THREAD

**Issue by verax-satya** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#12]
I'm using a Rpi 4B with two 1tb USB 3 drives. I have all of my OMV files on one of the drives, and I want to create a repo to periodically backup to the secondary drive. However, whenever I hit add and try to create a new local repository to backup my shared folder, I get this error.

"Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='hello' /usr/bin/borg init --encryption=none '/srv/dev-disk-by-label-drive/NAS/'' with exit code '2': "

Additionally, I noticed that 'initialization' is spelled wrong.

**Comment by ryecoaaron** [comment]
Were you using a new shared folder?  The folder has to be empty.

Typo fixed - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/a002620b3c21c8c74d07d731e1a7f9a7866b13cc

**Comment by verax-satya** [comment]
Looks like it was because I had '~/.profile' open in another tab! Thank you!
