### ISSUE TITLE
Borgserver fills up the rootfs partition on ARM

### ISSUE THREAD

**Issue by asitemade4u** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#13]
I am deploying OMV on an ARM 4 4GB RAM.
I then deployed the Borgserver plugin.
It works fine but it rapidly fills up the `rootfs` partition of the media card used to boot the system. As a result, the OMV server becomes unreliable and eventually stops working.
How can I avoid such a behavior?

**Comment by ryecoaaron** [comment]
I use this on arm and don't have this problem.

**Comment by asitemade4u** [comment]
My bad, I made a mistake while initializing the disk on OMV.

⁣S.​
