### ISSUE TITLE
Encryption support

### ISSUE THREAD

**Issue by tamasberes** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#16]
How does encryption support work? Where is the keyfile stored? Is it based on my OMV password or something?

**Comment by ryecoaaron** [comment]
The encryption is password based and there is no keyfile.  So, it is encrypted using whatever password you enter for the repo.

**Comment by slangdaddy** [comment]
Is this really true? I am just trying this out myself - setting up a server with borgmatic to backup into OMV. I found the keys of my repos (created with passphrase + encryption enabled in OMV) under ~/.config/borg/keys/

**Comment by ryecoaaron** [comment]
I guess I never went looking for a key file.  And when I read keyfile, I thought LUKS and how you can use a file as a keyfile instead of a password.
