### ISSUE TITLE
communication timeout when connecting ot large repository

### ISSUE THREAD

**Issue by ckolumbus** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#17]
I try to connect the `omv-borgbackup` to an existing remote repo containing the backup of  ~200GB images. 
After configuring the web ui, including `skipInit`, the plugin executes a `borg check` command ([see code](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/blob/0f4ea4b178c7654389b389e2757fa2a0d8b18f4c/usr/share/openmediavault/engined/rpc/borgbackup.inc#L137)). This results in a communication error, presumably because if executed from the command line, this check task >10 minutes to finish.

Any idea how I can extend the timeout or avoid this issue otherwise? Maybe repos this large might also cause issues when executing other commands on it as well. 

One possible solution would be to use the external `borgmatic` program for backing up this repository. Depending on the scope of omv-borgbackup. 

I'd be happy to hear your opinion on this issue.

**Comment by ryecoaaron** [comment]
The plugin can't change the timeout since that is an OMV-level setting.  I guess I could background the task.  This would just put the repo in a weird state where someone trying to create an archive before it is done would probably fail.

borgmatic is one option but that would be very different than the current plugin.  I guess I could look at making it a third tab in the current plugin or a separate plugin.  From a quick glance at the github repo, it looks like it would be a fairly simple plugin to make.

**Comment by ckolumbus** [comment]
@ryecoaaron thanks for the quick response. I can live with borgmatic from within the command line but wanted to make you and others aware of this possible problem. 

Backgrounding for creating the repo might be an option because of the weired UI vs repo state. I did some tests with other commands on the large repo: they seem not to be affected by the large amount of data, only the check. 

where else do you run `check` and why? maybe a faster test could be done (e.g only using `info`?). And a background check in case you explicitly trigger this from the ui.

**Comment by ryecoaaron** [comment]
check is only run when a check command is manually run on a repo from the Check menu.  These are run in the background though.  So, the timeout won't affect them.

I will look into borg info to see if that would work.  I assume that is fast on your system with the large repo?

**Comment by ckolumbus** [comment]
just verified: `borg info` is very fast.  

So the only remaining synchronous `check` call is on creating the repo with `skipInit`, I think this could be replaced with the `info` call.

**Comment by ryecoaaron** [comment]
5.1.6 is in the repo now.  It uses info instead of check for skipInit.  Let me know how that works for you.

**Comment by ckolumbus** [comment]
Just tested  the "add repo" : works like a charm! checking the backup itself tonight :-)
