### ISSUE TITLE
Remote-Repo Remote-Path Exit Code 2

### ISSUE THREAD

**Issue by honigwald** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#18]
I'm trying to create a borg backup of a remote server in the internet. 
Therefore I created a repo as shown in the first figure:
![image](https://user-images.githubusercontent.com/38533378/98387757-1b28d500-2052-11eb-9650-d51f093f1cf3.png)

It seems the pattern: root@hostname:path is not working correctly.
When I try to add the repo I get following error message.
![image](https://user-images.githubusercontent.com/38533378/98387903-50cdbe00-2052-11eb-8708-70ab3b43d6fa.png)

Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='' /usr/bin/borg init --encryption=none 'root@dummy.de:/home/'' with exit code '2':  in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/borgbackup.inc(156): OMV\System\Process->execute(Array)
#1 [internal function]: OMVRpcServiceBorgBackup->setRepo(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setRepo', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('BorgBackup', 'setRepo', Array, Array, 1)
#5 {main}

I tried it in many different ways without success. Is this a bug or am I doing anything wrong?
Kind regards.

PS: I'm running OMV 5.5.15-1

**Comment by auanasgheps** [comment]
I have the same issue. If you remove the path and enter `root@dummy.de`, does it save correctly?
I know it will miss the path, but looks like the plugin accepts it.

**Comment by honigwald** [comment]
> I have the same issue. If you remove the path and enter `root@dummy.de`, does it save correctly?
> I know it will miss the path, but looks like the plugin accepts it.

Yes, than it saves correctly. It also saves, when I save `root@dummy.de:` but the borg-backup isn't able to find anything in the given path. (I expected it will search in home-dir)

**Comment by ryecoaaron** [comment]
see issue #19 - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/issues/19.  The code works.  I use it.  Remote setups require setup outside the plugin (impossible to do with the plugin).

**Comment by auanasgheps** [comment]
@honigwald see the guide I've published [here](https://forum.openmediavault.org/index.php?thread/36602-how-to-borg-backup/#), might help you with the setup

**Comment by honigwald** [comment]
> @honigwald see the guide I've published [here](https://forum.openmediavault.org/index.php?thread/36602-how-to-borg-backup/#), might help you with the setup

Thank you for your reply. I think I got this plugin totally wrong. I don't want to backup my OMV to a remote System (Server), but do it vice-versa. The system I want to backup is a Debian Server located in the Internet. The backup sink is my OMV located in my LAN. Since my OMV is not running all the time, I want to start the backup process from the sink (OMV). I'm afraid the only option for that is to mount the remote filesystem (e.g through sshfs) and execute a local backup on OMV.

**Comment by auanasgheps** [comment]
If you want to do this, you don't really need the OMV plugin.
The Borg "server" almost requires zero backup (install Borg + configure SSH properly).
You could schedule to start the backup from the remote server with cron when you know your OMV server is up.
