### ISSUE TITLE
Unable to run command for custom port

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#19]
Hi!
I am trying to setup borg connecting to a server with a custom SSH port.
The plugin specifies the format is `user@host:/path` but this command does not allow for custom port.
I need to run `ssh://user@host:port/path/to/repo` but the plugin errors out with a generic error. 

If I run the command that fails in shell, It runs. Is there a way to get more info from this error? I can't see a log for borg.

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='pass' /usr/bin/borg init --encryption=keyfile 'ssh://borg@xxxxxxxxxxxxx:9876/volume1/Backup'' with exit code '2':
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; BORG_PASSPHRASE='pass' /usr/bin/borg init --encryption=keyfile 'ssh://borg@xxxxxxxxxxxxx:9876/volume1/Backup'' with exit code '2':  in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/borgbackup.inc(156): OMV\System\Process->execute(Array)
#1 [internal function]: OMVRpcServiceBorgBackup->setRepo(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('setRepo', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('BorgBackup', 'setRepo', Array, Array, 1)
#5 {main}

```

**Comment by ryecoaaron** [comment]
The plugin doesn't do anything special with the remote path.  I know the code works because I use it.  There are a couple of things that I can think of.  Do you have borg installed on the remote end?  The command runs as root and the ssh key for the remote server will need to be accept as root on the local server.  The plugin can't do this.

**Comment by auanasgheps** [comment]
Please discard this issue.
I didn't know what I had to do, I thought this plugin was reading the SSH Key from OMV `Certificates > SSH`. Maybe some docs would have helped (It's the first plugin I've found without docs)

Borg was installed on the remote end but the SSH key wasn't properly installed.

In the meantime I've discovered `borgmatic`, which is extremely simple to setup and flexible.

**Comment by ryecoaaron** [comment]
The plugin would only use Certs from Certificates > SSH if there was a dropdown to select one.  The borgbackup command doesn't have a way to specify a cert that I know.  So, I can't add this.

As for docs, I rely on others to create guides and docs.  Borg has excellent docs that should match what the plugin is doing - https://borgbackup.readthedocs.io/en/stable/usage/general.html.  I just don't have time (and not good at it) to make docs that noobs would benefit from.

Borgmatic is simple and flexible and I considered making a plugin with it.  But, the plugin can do much more therefore harder to use.

**Comment by auanasgheps** [comment]
I agree that other people should make docs, then  not many (noobs) are using the borg plugin. 
I felt a bit confused because there were too many options and I wasn't familiar with borg (noob).

Then I discovered borgmatic and I like it a lot. 
I don't think you should need to make a borgmatic plugin since it's just a yaml config and a couple of commands, instead I see the point of making a borg plugin.

**Comment by ryecoaaron** [comment]
@auanasgheps the reason I liked the idea of a borgmatic plugin is because it would be so much simpler for noobs to understand.

**Comment by auanasgheps** [comment]
I understand. 
I am new in the borg/borgbackup world but I love how quick and smart is.

You can count on my help if you'll need documentation for a borgbackup plugin.

I guess the new plugin could replace the current one, and not bee too much work as you would essentially need to map in UI fields from the YAML config and map the other commands.

Little tip: `borgbackup` in the buster repo is extremely old. `Borg `too, but there's buster-backports available.

**Comment by ryecoaaron** [comment]
@auanasgheps 

The borgbackup plugin will stay.  I just meant there might be an additional borgmatic plugin OR maybe a borgmatic tab in the borgbackup plugin

It would be great if you could create some docs for the borgbackup plugin.  I don't have the time and my skills for writing something a noob understands are poor.

As for borgbackup being old, that is why omv-extras pins the version from backports (made the change in Sept 2019) - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/blob/master/srv/salt/omv/deploy/omvextras/files/etc-apt-preferences_d-omvextras_pref.j2#L33

**Comment by auanasgheps** [comment]
Sorry I had a brain fart: when I wrote borgbackup I meant borgmatic, and when I wrote borg I meant borgbackup.

Nevertheless, I am working on a guide as promised. 

How often the plugin creates a backup? I can't see a scheduling option but I am sure you scheduled it. 

When the guide will be ready, should I simply post it in the Forums > Plugins section or you want it somewhere else?

**Comment by ryecoaaron** [comment]
When you create an archive, you determine the schedule.
When it is ready, you can create a post in the Forum -> Guides section.

**Comment by auanasgheps** [comment]
When I create the archive I don't see an option for for the schedule.

Is this the Borg retention policy?
![image](https://user-images.githubusercontent.com/20586878/98858454-e86f4a00-2460-11eb-9af4-1157adca7a51.png)

**Comment by ryecoaaron** [comment]
True. that is the retention policy.  The plugin is just like rsnapshot.  They are designed to run all the time.  So, here is the schedule - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/blob/master/srv/salt/omv/deploy/borgbackup/files/etc-cron_d-openmediavault-borgbackup.j2

**Comment by auanasgheps** [comment]
I configured an archive, waited for a while an nothing happened at 5 past the hour, even if the job triggered.

![image](https://user-images.githubusercontent.com/20586878/98871280-ed3df900-2474-11eb-83f4-b2b1b81a03e2.png)
However, when I did run (for the first time) the archive it ran successfully.

Do I need to run it the first time by hand? I guess I'll find it out in one hour, but wanted to know if this is by design.

**Comment by ryecoaaron** [comment]
While the cron job runs every hour, the archive will only run as frequently as the first non-zero retention policy.  So, if you have hourly set to zero and daily set to greater than zero, the archives will happen daily.  If hourly and daily are set to zero and weekly is greater than zero, then the archives will happen weekly.  The fact that the cron job runs hourly but doesn't do anything in those cases shouldn't case any problems.

If you are running a remote job that hasn't accepted the ssh cert, that is a different issue.

**Comment by auanasgheps** [comment]
Super clear Aaron, thanks! I have documented this behavior as well.
I've posted the guide, it's here:
https://forum.openmediavault.org/index.php?thread/36602-how-to-borg-backup/

Please, make changes if required.

> If you are running a remote job that hasn't accepted the ssh cert, that is a different issue.

Of course, I am aware of this.
