### ISSUE TITLE
Mounting repo creates a folder which contains single quotes in path

### ISSUE THREAD

**Issue by mohahn** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#2]
Using OMV 4.1.20. Backup is working fine so far. Also mounting repo to shared folder works, but additionally a folder is created which contains single quotes. For example the following statement is executed when mounting repo:

`/usr/bin/borg mount '/srv/dev-disk-by-id-md-name-nas-1/backup/docker' '/srv/dev-disk-by-id-md-name-nas-0/restore/docker'`

Backup data can be found in `/srv/dev-disk-by-id-md-name-nas-0/restore/docker`
For an unknown reason, a folder with path `/'/srv/dev-disk-by-id-md-name-nas-0/restore/docker/'` is created too, which is empty

**Comment by ryecoaaron** [comment]
Fixed in 4.0.2 in the repo now.
