### ISSUE TITLE
can anyone help me?

### ISSUE THREAD

**Issue by Santolo2001** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#21]
I installed the openVPN plugin in OpenMediaVault only that when I start it, this error comes up:

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color openvpn 2>&1' with exit code '1': raspberrypi: ---------- ID: stop_openvpn_service Function: service.dead Name: openvpn Result: True Comment: The service openvpn is already dead Started: 18:28:39.887686 Duration: 222.163 ms Changes: ---------- ID: setup_openvpn Function: cmd.run Name: /usr/sbin/omv-openvpn setup Result: False Comment: Device "eth0" does not exist. /usr/sbin/omv-openvpn: line 47: 5 - ( / 8) : syntax error: operand expected (error token is "/ 8) ") iptables v1.8.2 (nf_tables): option "--to" requires an argument Try `iptables -h' or 'iptables --help' for more information. Started: 18:28:40.115560 Duration: 2449.202 ms Changes: ---------- ID: start_openvpn_service Function: service.running Name: openvpn Result: False Comment: One or more requisite failed: omv.deploy.openvpn.default.setup_openvpn Started: 18:28:42.567141 Duration: 0.03 ms Changes: Summary for raspberrypi ------------ Succeeded: 1 Failed: 2 ------------ Total states run: 3 Total run time: 2.671 s

someone can help me because I'm not very good at these things

**Comment by ryecoaaron** [comment]
An openvpn issue on the borgbackup issue page?  Please post in the forum - https://forum.openmediavault.org/
