### ISSUE TITLE
Error While Appling Settings

### ISSUE THREAD

**Issue by neelgpatel0510** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#24]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color fstab 2>&1' with exit code '1': raspberrypi: ---------- ID: create_filesystem_mountpoint_945605ce-af51-44c1-b3e9-a0235fa5de03 Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_945605ce-af51-44c1-b3e9-a0235fa5de03 for file /etc/fstab was charged by text Started: 21:04:55.909081 Duration: 2.555 ms Changes: ---------- ID: mount_filesystem_mountpoint_945605ce-af51-44c1-b3e9-a0235fa5de03 Function: mount.mounted Name: /srv/dev-disk-by-uuid-7d861a87-5201-40fe-bbe6-4aa81f4eb63e Result: True Comment: Started: 21:04:55.913833 Duration: 164.211 ms Changes: ---------- ID: create_filesystem_mountpoint_c1ad8e2e-8a28-48b9-9580-582cdb3e7b3b Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_c1ad8e2e-8a28-48b9-9580-582cdb3e7b3b for file /etc/fstab was charged by text Started: 21:04:56.078817 Duration: 3.289 ms Changes: ---------- ID: mount_filesystem_mountpoint_c1ad8e2e-8a28-48b9-9580-582cdb3e7b3b Function: mount.mounted Name: /srv/dev-disk-by-uuid-cbc47dc3-1002-4f24-851c-705565960269 Result: True Comment: Started: 21:04:56.082489 Duration: 98.65 ms Changes: ---------- ID: create_filesystem_mountpoint_ccc1723b-e540-42ef-b9f1-23506cce768e Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_ccc1723b-e540-42ef-b9f1-23506cce768e for file /etc/fstab was charged by text Started: 21:04:56.181898 Duration: 3.203 ms Changes: ---------- ID: mount_filesystem_mountpoint_ccc1723b-e540-42ef-b9f1-23506cce768e Function: mount.mounted Name: /srv/dev-disk-by-uuid-3c6a3877-aa77-40c9-ab14-4bf5711d5d80 Result: True Comment: Target was already mounted Started: 21:04:56.185490 Duration: 165.995 ms Changes: ---------- umount: Forced remount because options (user_xattr) changed ---------- ID: create_bind_mountpoint_7ef14826-2f5b-47a8-8a29-647f7e7447d0 Function: file.accumulated Result: True Comment: Accumulator create_bind_mountpoint_7ef14826-2f5b-47a8-8a29-647f7e7447d0 for file /etc/fstab was charged by text Started: 21:04:56.352228 Duration: 3.76 ms Changes: ---------- ID: mount_bind_mountpoint_7ef14826-2f5b-47a8-8a29-647f7e7447d0 Function: mount.mounted Name: /export/NAS Result: False Comment: mount: /export/NAS: special device /srv/dev-disk-by-uuid-7d861a87-5201-40fe-bbe6-4aa81f4eb63e/NAS/ does not exist. Started: 21:04:56.356432 Duration: 107.92 ms Changes: ---------- ID: append_fstab_entries Function: file.blockreplace Name: /etc/fstab Result: True Comment: No changes needed to be made Started: 21:04:56.469479 Duration: 13.978 ms Changes: Summary for raspberrypi ------------ Succeeded: 8 (changed=1) Failed: 1 ------------ Total states run: 9 Total run time: 563.561 ms

**Comment by ryecoaaron** [comment]
Please post on the forum. Your system is having an issue with a mount point. The plugin can’t do anything about that.
