### ISSUE TITLE
Show existing archives when adding repository

### ISSUE THREAD

**Issue by wnhre2ur8cxx8** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#25]
I just added an already existing repository and everything worked as expected. Except that the archives are not showing up. I guess they are stored somehwere externally as soon as you execute them or something? Or is this a bug and it should show up?

I am using the latest omv 5

**Comment by ryecoaaron** [comment]
Closing because I can't add archives to the database to show up on the Archives tab because I don't have scheduled info for them.
