### ISSUE TITLE
Failed to execute XPath query '//services/borgbackup/repos/repo[uuid='<private-info>']'.

### ISSUE THREAD

**Issue by diogogomes** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#28]
Hello,

I am using your plugin for two months and today after clicking on the plugin option I get the error Failed to execute XPath query '//services/borgbackup/repos/repo[uuid='...']' and all entries in Archives tab are gone.

---

## System info:

**OMV version:** 5.6.21-2
**BorgBackup plugin:** 5.1.9

---

## Detailed error:

```
Error #0:
OMV\Config\DatabaseException: Failed to execute XPath query '//services/borgbackup/repos/repo[uuid='<private-info>']'. in /usr/share/php/openmediavault/config/database.inc:78
Stack trace:
#0 /usr/share/openmediavault/engined/rpc/borgbackup.inc(327): OMV\Config\Database->get('conf.service.bo...', '<private-info>')
#1 [internal function]: OMVRpcServiceBorgBackup->getArchiveList(Array, Array)
#2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getArchiveList', Array, Array)
#4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('BorgBackup', 'getArchiveList', Array, Array, 1)
#5 {main}
```

---

Due to the importance of backups and being a production environment, I have uninstalled the plugin and will use pure Borg but I am available to help debug on another installation if you wish.

Thank you for the development of your plugin.

**Comment by ryecoaaron** [comment]
Did you delete a repo that archives were associated with?  The plugin does not prevent this.  I would need to see the output of:  sudo omv-showkey borgbackup

**Comment by diogogomes** [comment]
> Did you delete a repo that archives were associated with? The plugin does not prevent this.

I deleted a new repository but all the files from the other repositories are also gone.

> I would need to see the output of: sudo omv-showkey borgbackup

I get a "command not found" maybe because I already uninstalled the plugin. (I'm ok with closing this issue if it is no longer possible to debug)

**Comment by ryecoaaron** [comment]
The problem I am thinking about wouldn’t care about files. The plugin has a repo tab and an archives tab. Each archive on the archives tab has to be associated with a repo on the repo tab. If you delete a repo from the repo tab that is associated with one or more archives on the archives tab, you will probably break the archives tab.

omv-showkey is installed by omv-extras itself. But if you uninstalled the plugin, the info I need is gone. You could reinstall it and it should work again. just make sure to ctrl-shift-R after re-installing.

**Comment by diogogomes** [comment]
> If you delete a repo from the repo tab that is associated with one or more archives on the archives tab, you will probably break the archives tab.

It seems that's what happened. I deleted the repository I didn't want and it broke the Archives tab.

I suggest a mechanism to prevent this problem because in cases like mine, I stopped having access to the files of the remaining repositories through the plugin.

Thank you for your support.

**Comment by ryecoaaron** [comment]
I knew it was a problem but it is a pain to prevent.  I didn't think people would delete a repo that still had active archives.  This doesn't break borg.  It only breaks the web interface.  Your files aren't affected by this.

**Comment by ryecoaaron** [comment]
Closed with commit https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/36469350aa595c62f7c3fbd0327a05eb62c5d356
