### ISSUE TITLE
one-filesystem has no effect on borg create command

### ISSUE THREAD

**Issue by niko2** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#3]
Either I select one filesystem or not, there is no option in generated borg script

**Comment by ryecoaaron** [comment]
It is only used when creating an archive - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/blob/master/usr/share/openmediavault/engined/rpc/borgbackup.inc#L396

The output window should show the full command line and arguments.  What are you seeing?  What effect are you expecting that it is not doing?

**Comment by niko2** [comment]
Hello,
Even when using one filesystem (it is displayed well when i run an archive manually) for /, all other filesystems are taking part of the archive. I suspect a borg bug then. Or something I don't well understand with this option (however it is obvious !)

**Comment by ryecoaaron** [comment]
This should be fixed on 5.0.2 in the repo now.
