### ISSUE TITLE
Feature-Request: Integration of borgbackup log into omv gui

### ISSUE THREAD

**Issue by trashcoder** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#30]
Actually it's not possible to see, if a backup is still running or other information of a log from the gui of omv after you logged off from omv and later logged in again.

it would be convenient to the user if he could see this log or the the actual status of his running backup within omv from a menu button.

**Comment by ryecoaaron** [comment]
It doesn't have a log viewer since borg has multi-line logs and doesn't put a timestamp on each line.  So, it doesn't work very well in the OMV log viewer.   Scheduled jobs will have the results emailed to you unless you disable them.
