### ISSUE TITLE
upgraded OMV6 no borgbackup in GUI

### ISSUE THREAD

**Issue by Cupropituvanso** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#31]
Hello

I have upgraded OMV 4 > 5 > 6 and then tried to install borgbackup via gui. The installation seems successfully, but there is no borgbackup in the gui.
In the CLI borgbackup seems installed:

```
omv-salt deploy run borgbackup
treasury.KCA:
----------
          ID: configure_borg_hourly_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/hourly.d
      Result: True
     Comment: The directory /var/lib/openmediavault/borgbackup/hourly.d is in the correct state
     Started: 00:10:21.090060
    Duration: 9.046 ms
     Changes:   
[...]
Summary for treasury.KCA
------------
Succeeded: 6
Failed:    0
------------
Total states run:     6
Total run time:  65.061 ms

borgbackup
usage: borgbackup [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug] [--debug-topic TOPIC] [-p] [--log-json]
                  [--lock-wait SECONDS] [--bypass-lock] [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
                  [--remote-ratelimit RATE] [--consider-part-files] [--debug-profile FILE] [--rsh RSH]
                  <command> ...
```

**Comment by ryecoaaron** [comment]
Did you hit ctrl-shift-R? what is the output of: dpkg -l | grep borg

**Comment by Cupropituvanso** [comment]
Yes, Browsercache reloaded and even tried a different browser.

```
dpkg -l | grep borg
ii  borgbackup                      1.1.16-3                       amd64        deduplicating and compressing backup program
ii  openmediavault-borgbackup       5.1.9                          all          borgbackup plugin for OpenMediaVault.
```

**Comment by ryecoaaron** [comment]
You somehow installed the omv 5.x version on omv 6.x. Your upgrade was not completely successful. Maybe my fix script would help - https://github.com/OpenMediaVault-Plugin-Developers/installScript/blob/master/fix5to6upgrade

**Comment by Cupropituvanso** [comment]
Thanks, worked!

**Comment by chocmake** [comment]
Encountering something similar. I upgraded from OMV v6 to v7 (via `omv-release-upgrade`) and also ran the `fix6to7upgrade` script twice as I'd seen recommended.

However despite having OMV Extras installed (and various plugins from OMV Extras I already have installed carrying over) there are no results in the *System>Plugins* section, even after clicking 'Check for new plugins' and force reloading page.

Any ideas?

**Comment by ryecoaaron** [comment]
@chocmake this would be easier to support on the forum instead of a closed issue.  It isn't a problem with the borg plugin and yes, it is compatible with OMV 7.  I would need output from the fix6to7upgrade script and the output of "sudo omv-aptclean repos"

**Comment by chocmake** [comment]
> `fix6to7upgrade` output:

<details>
<code><pre>
Removing old sources ...
Installing omv-extras 7.x ...
Clearing cache ...
local:
    True
Change to bullseye and shaitan just in case ...
Fixing Debian security repo ...
deb http://security.debian.org/debian-security bookworm-security main contrib no                        n-free
Running apt-get update ...
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:5 http://security.debian.org/debian-security bookworm-security InRelease [48                        .0 kB]
Hit:6 http://deb.debian.org/debian bookworm InRelease
Get:7 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:8 https://openmediavault.github.io/packages sandworm InRelease [12.8 kB]
Get:9 http://httpredir.debian.org/debian bookworm-backports InRelease [59.0 kB]
Get:10 https://openmediavault.github.io/packages sandworm/main amd64 Packages [8                        398 B]
Get:11 http://httpredir.debian.org/debian bookworm-backports/main amd64 Packages                        .diff/Index [63.3 kB]
Get:12 http://httpredir.debian.org/debian bookworm-backports/main Translation-en                        .diff/Index [63.3 kB]
Get:13 http://packages.openmediavault.org/public sandworm InRelease [12.8 kB]
Get:14 http://httpredir.debian.org/debian bookworm-backports/main amd64 Packages                         T-2024-11-02-2033.42-F-2024-11-02-2033.42.pdiff [3785 B]
Get:14 http://httpredir.debian.org/debian bookworm-backports/main amd64 Packages                         T-2024-11-02-2033.42-F-2024-11-02-2033.42.pdiff [3785 B]
Get:15 http://httpredir.debian.org/debian bookworm-backports/main Translation-en                         T-2024-11-02-2033.42-F-2024-11-02-2033.42.pdiff [1626 B]
Get:15 http://httpredir.debian.org/debian bookworm-backports/main Translation-en                         T-2024-11-02-2033.42-F-2024-11-02-2033.42.pdiff [1626 B]
Get:16 http://packages.openmediavault.org/public sandworm/main amd64 Packages [8                        398 B]
Fetched 337 kB in 1s (241 kB/s)
Reading package lists... Done
Running apt-get dist-upgrade ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  linux-image-6.1.0-0.deb11.21-amd64
Use 'apt autoremove' to remove it.
The following packages will be upgraded:
  openmediavault
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3055 kB of archives.
After this operation, 45.1 kB of additional disk space will be used.
Get:1 http://packages.openmediavault.org/public sandworm/main amd64 openmediavau                        lt all 7.4.11-1 [3055 kB]
Fetched 3055 kB in 3s (976 kB/s)
Preconfiguring packages ...
(Reading database ... 114200 files and directories currently installed.)
Preparing to unpack .../openmediavault_7.4.11-1_all.deb ...
Unpacking openmediavault (7.4.11-1) over (7.4.10-1) ...
Setting up openmediavault (7.4.11-1) ...
Creating configuration database ...
Migrating configuration database ...
Setting up Salt environment ...
Processing system modifications ...
Processing triggers for rsyslog (8.2302.0-1) ...
Processing triggers for openmediavault (7.4.11-1) ...
Restarting engine daemon ...
Updating workbench configuration files ...
removed '/usr/sbin/omv-mkaptidx'
Downloading omv-mkaptidx...
Rebuild apt index ...
debian:
----------
          ID: disable_ssh_socket_activation
    Function: service.dead
        Name: ssh.socket
      Result: True
     Comment: The service ssh.socket is already dead
     Started: 18:23:40.453162
    Duration: 52.402 ms
     Changes:
----------
          ID: remove_ssh_authorized_keys
    Function: file.directory
        Name: /var/lib/openmediavault/ssh/authorized_keys
      Result: True
     Comment: Files cleaned from directory /var/lib/openmediavault/ssh/authorize                        d_keys
     Started: 18:23:40.507070
    Duration: 1.47 ms
     Changes:
              ----------
              /var/lib/openmediavault/ssh/authorized_keys/omv-share:
                  ----------
                  removed:
                      Removed due to clean
              /var/lib/openmediavault/ssh/authorized_keys/omv-share-sub:
                  ----------
                  removed:
                      Removed due to clean
              /var/lib/openmediavault/ssh/authorized_keys/user:
                  ----------
                  removed:
                      Removed due to clean
              removed:
                  - /var/lib/openmediavault/ssh/authorized_keys/omv-share-sub
                  - /var/lib/openmediavault/ssh/authorized_keys/user
                  - /var/lib/openmediavault/ssh/authorized_keys/omv-share
----------
          ID: create_ssh_authorized_key_file_user
    Function: file.managed
        Name: /var/lib/openmediavault/ssh/authorized_keys/user
      Result: True
     Comment: File /var/lib/openmediavault/ssh/authorized_keys/user updated
     Started: 18:23:40.508632
    Duration: 1.906 ms
     Changes:
              ----------
              diff:
                  New file
              user:
                  user
----------
          ID: create_tmp_pubkey_file_user_1
    Function: file.managed
        Name: /tmp/tmpnd_524vu
      Result: True
     Comment: File /tmp/tmpnd_524vu updated
     Started: 18:23:40.510629
    Duration: 42.215 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -0,0 +1,9 @@
                  +---- BEGIN SSH2 PUBLIC KEY ----
                  <snip>
                  +---- END SSH2 PUBLIC KEY ----
----------
          ID: append_ssh_authorized_key_user_1
    Function: cmd.run
        Name: ssh-keygen -i -f '/tmp/tmpnd_524vu' >> '/var/lib/openmediavault/ss                        h/authorized_keys/user'
      Result: True
     Comment: Command "ssh-keygen -i -f '/tmp/tmpnd_524vu' >> '/var/lib/openmedi                        avault/ssh/authorized_keys/user'" run
     Started: 18:23:40.553464
    Duration: 19.087 ms
     Changes:
              ----------
              pid:
                  2746
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: remove_tmp_pubkey_file_user_1
    Function: file.absent
        Name: /tmp/tmpnd_524vu
      Result: True
     Comment: Removed file /tmp/tmpnd_524vu
     Started: 18:23:40.572672
    Duration: 0.53 ms
     Changes:
              ----------
              removed:
                  /tmp/tmpnd_524vu
----------
          ID: create_ssh_authorized_key_file_omv-share
    Function: file.managed
        Name: /var/lib/openmediavault/ssh/authorized_keys/omv-share
      Result: True
     Comment: File /var/lib/openmediavault/ssh/authorized_keys/omv-share updated
     Started: 18:23:40.573345
    Duration: 1.711 ms
     Changes:
              ----------
              diff:
                  New file
              user:
                  omv-share
----------
          ID: create_ssh_authorized_key_file_omv-share-sub
    Function: file.managed
        Name: /var/lib/openmediavault/ssh/authorized_keys/omv-share-sub
      Result: True
     Comment: File /var/lib/openmediavault/ssh/authorized_keys/omv-share-sub upd                        ated
     Started: 18:23:40.575186
    Duration: 1.677 ms
     Changes:
              ----------
              diff:
                  New file
              user:
                  omv-share-sub
----------
          ID: configure_sshd_config
    Function: file.managed
        Name: /etc/ssh/sshd_config
      Result: True
     Comment: File /etc/ssh/sshd_config is in the correct state
     Started: 18:23:40.576955
    Duration: 105.094 ms
     Changes:
----------
          ID: divert_sshd_config
    Function: omv_dpkg.divert_add
        Name: /etc/ssh/sshd_config
      Result: True
     Comment: Leaving 'local diversion of /etc/ssh/sshd_config to /etc/ssh/sshd_                        config.distrib'
     Started: 18:23:40.682756
    Duration: 7.642 ms
     Changes:
----------
          ID: create_sshd_runtime_dir
    Function: file.directory
        Name: /run/sshd
      Result: True
     Comment: The directory /run/sshd is in the correct state
     Started: 18:23:40.690500
    Duration: 0.763 ms
     Changes:
----------
          ID: test_sshd_config
    Function: cmd.run
        Name: sshd -t
      Result: True
     Comment: Command "sshd -t" run
     Started: 18:23:40.691350
    Duration: 11.476 ms
     Changes:
              ----------
              pid:
                  2749
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: start_ssh_service
    Function: service.running
        Name: ssh
      Result: True
     Comment: The service ssh is already running
     Started: 18:23:40.703128
    Duration: 19.629 ms
     Changes:
----------
          ID: cleanup_monit_conf_dir
    Function: module.run
      Result: True
     Comment: file.find: ['/etc/monit/conf.d/openmediavault-collectd.conf', '/et                        c/monit/conf.d/openmediavault-engined.conf', '/etc/monit/conf.d/openmediavault-f                        ilesystem.conf', '/etc/monit/conf.d/openmediavault-nginx.conf', '/etc/monit/conf                        .d/openmediavault-nut.conf', '/etc/monit/conf.d/openmediavault-phpfpm.conf', '/e                        tc/monit/conf.d/openmediavault-rrdcached.conf', '/etc/monit/conf.d/openmediavaul                        t-system.conf']
     Started: 18:23:40.723351
    Duration: 1.188 ms
     Changes:
              ----------
              file.find:
                  - /etc/monit/conf.d/openmediavault-collectd.conf
                  - /etc/monit/conf.d/openmediavault-engined.conf
                  - /etc/monit/conf.d/openmediavault-filesystem.conf
                  - /etc/monit/conf.d/openmediavault-nginx.conf
                  - /etc/monit/conf.d/openmediavault-nut.conf
                  - /etc/monit/conf.d/openmediavault-phpfpm.conf
                  - /etc/monit/conf.d/openmediavault-rrdcached.conf
                  - /etc/monit/conf.d/openmediavault-system.conf
----------
          ID: configure_default_monit
    Function: file.managed
        Name: /etc/default/monit
      Result: True
     Comment: File /etc/default/monit is in the correct state
     Started: 18:23:40.724623
    Duration: 35.015 ms
     Changes:
----------
          ID: divert_default_monit
    Function: omv_dpkg.divert_add
        Name: /etc/default/monit
      Result: True
     Comment: Leaving 'local diversion of /etc/default/monit to /etc/default/mon                        it.distrib'
     Started: 18:23:40.759728
    Duration: 7.331 ms
     Changes:
----------
          ID: configure_monit_monitrc
    Function: file.managed
        Name: /etc/monit/monitrc
      Result: True
     Comment: File /etc/monit/monitrc is in the correct state
     Started: 18:23:40.767153
    Duration: 93.291 ms
     Changes:
----------
          ID: divert_monit_monitrc
    Function: omv_dpkg.divert_add
        Name: /etc/monit/monitrc
      Result: True
     Comment: Leaving 'local diversion of /etc/monit/monitrc to /etc/monit/monit                        rc.distrib'
     Started: 18:23:40.860539
    Duration: 7.412 ms
     Changes:
----------
          ID: configure_monit_collectd_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-collectd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-collectd.conf updated
     Started: 18:23:40.868050
    Duration: 88.1 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_filesystem_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-filesystem.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf updated
     Started: 18:23:40.956239
    Duration: 95.64 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_nginx_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nginx.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nginx.conf updated
     Started: 18:23:41.051968
    Duration: 88.567 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_nut_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nut.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nut.conf updated
     Started: 18:23:41.140622
    Duration: 93.02 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_omv-engined_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-engined.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-engined.conf updated
     Started: 18:23:41.233734
    Duration: 86.272 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_php-fpm_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf updated
     Started: 18:23:41.320094
    Duration: 86.783 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_rrdcached_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf updated
     Started: 18:23:41.406962
    Duration: 86.216 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_monit_system_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-system.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-system.conf updated
     Started: 18:23:41.493309
    Duration: 97.929 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: test_monit_config
    Function: cmd.run
        Name: monit -t
      Result: True
     Comment: Command "monit -t" run
     Started: 18:23:41.591324
    Duration: 7.717 ms
     Changes:
              ----------
              pid:
                  2755
              retcode:
                  0
              stderr:
              stdout:
                  Control file syntax OK
----------
          ID: reload_monit_service
    Function: service.running
        Name: monit
      Result: True
     Comment: Service reloaded
     Started: 18:23:41.628063
    Duration: 74.26 ms
     Changes:
              ----------
              monit:
                  True
----------
          ID: configure_nginx_site_webgui
    Function: file.managed
        Name: /etc/nginx/sites-available/openmediavault-webgui
      Result: True
     Comment: File /etc/nginx/sites-available/openmediavault-webgui is in the co                        rrect state
     Started: 18:23:41.702454
    Duration: 101.079 ms
     Changes:
----------
          ID: configure_nginx_security
    Function: file.managed
        Name: /etc/nginx/openmediavault-webgui.d/security.conf
      Result: True
     Comment: File /etc/nginx/openmediavault-webgui.d/security.conf is in the co                        rrect state
     Started: 18:23:41.803627
    Duration: 93.316 ms
     Changes:
----------
          ID: execute_nginx_ensite
    Function: cmd.run
        Name: nginx_ensite openmediavault-webgui
      Result: True
     Comment: Command "nginx_ensite openmediavault-webgui" run
     Started: 18:23:41.897033
    Duration: 3.793 ms
     Changes:
              ----------
              pid:
                  2769
              retcode:
                  0
              stderr:
              stdout:
                  Site configuration file 'openmediavault-webgui' is already ena                        bled.
----------
          ID: test_nginx_service_config
    Function: cmd.run
        Name: nginx -t
      Result: True
     Comment: Command "nginx -t" run
     Started: 18:23:41.900910
    Duration: 5.809 ms
     Changes:
              ----------
              pid:
                  2770
              retcode:
                  0
              stderr:
                  nginx: the configuration file /etc/nginx/nginx.conf syntax is                         ok
                  nginx: configuration file /etc/nginx/nginx.conf test is succes                        sful
              stdout:
----------
          ID: restart_nginx_service
    Function: service.running
        Name: nginx
      Result: True
     Comment: The service nginx is already running
     Started: 18:23:41.907291
    Duration: 19.241 ms
     Changes:
----------
          ID: monitor_nginx_service
    Function: module.run
      Result: True
     Comment: monit.monitor: True
     Started: 18:23:41.926941
    Duration: 7.405 ms
     Changes:
              ----------
              monit.monitor:
                  True
----------
          ID: configure_phpfpm_webgui
    Function: file.managed
        Name: /etc/php/8.2/fpm/pool.d/openmediavault-webgui.conf
      Result: True
     Comment: File /etc/php/8.2/fpm/pool.d/openmediavault-webgui.conf is in the                         correct state
     Started: 18:23:41.934472
    Duration: 35.65 ms
     Changes:
----------
          ID: test_phpfpm_service_config
    Function: cmd.run
        Name: php-fpm8.2 --test
      Result: True
     Comment: Command "php-fpm8.2 --test" run
     Started: 18:23:41.970222
    Duration: 46.628 ms
     Changes:
              ----------
              pid:
                  2779
              retcode:
                  0
              stderr:
                  [02-Nov-2024 18:23:42] NOTICE: configuration file /etc/php/8.2                        /fpm/php-fpm.conf test is successful
              stdout:
----------
          ID: restart_phpfpm_service
    Function: service.running
        Name: php8.2-fpm
      Result: True
     Comment: The service php8.2-fpm is already running
     Started: 18:23:42.017351
    Duration: 19.163 ms
     Changes:
----------
          ID: monitor_phpfpm_service
    Function: module.run
      Result: True
     Comment: monit.monitor: True
     Started: 18:23:42.036862
    Duration: 7.085 ms
     Changes:
              ----------
              monit.monitor:
                  True

Summary for debian
-------------
Succeeded: 38 (changed=24)
Failed:     0
-------------
Total states run:     38
Total run time:    1.554 s
Done.

</pre></code>
</details>

> `sudo omv-aptclean repos` output

<details>
<code><pre>
1. Cleaning apt cache files...

2. Clearing available dpkg packages...

3. Removing apt lists...
removed '/var/lib/apt/lists/_var_cache_openmediavault_archives_Packages'
removed directory '/var/lib/apt/lists/auxfiles'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_InRelease'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_contrib_binary-amd64_Packages'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_contrib_i18n_Translation-en'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_contrib_source_Sources'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_main_binary-amd64_Packages'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_main_i18n_Translation-en'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_main_source_Sources'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_non-free_binary-amd64_Packages'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_non-free_i18n_Translation-en'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm-updates_non-free_source_Sources'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm_InRelease'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm_main_binary-amd64_Packages'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm_main_i18n_Translation-en'
removed '/var/lib/apt/lists/deb.debian.org_debian_dists_bookworm_main_source_Sources'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_InRelease'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_contrib_binary-amd64_Packages'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_contrib_i18n_Translation-en'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_main_binary-amd64_Packages'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_main_binary-amd64_Packages.diff_Index'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_main_i18n_Translation-en'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_main_i18n_Translation-en.diff_Index'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_non-free-firmware_binary-amd64_Packages'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_non-free-firmware_i18n_Translation-en'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_non-free_binary-amd64_Packages'
removed '/var/lib/apt/lists/httpredir.debian.org_debian_dists_bookworm-backports_non-free_i18n_Translation-en'
removed '/var/lib/apt/lists/lock'
removed '/var/lib/apt/lists/openmediavault.github.io_packages_dists_sandworm_InRelease'
removed '/var/lib/apt/lists/openmediavault.github.io_packages_dists_sandworm_main_binary-amd64_Packages'
removed '/var/lib/apt/lists/packages.openmediavault.org_public_dists_sandworm_InRelease'
removed '/var/lib/apt/lists/packages.openmediavault.org_public_dists_sandworm_main_binary-amd64_Packages'
removed directory '/var/lib/apt/lists/partial'
removed '/var/lib/apt/lists/security.debian.org_debian-security_dists_bookworm-security_InRelease'
removed '/var/lib/apt/lists/security.debian.org_debian-security_dists_bookworm-security_contrib_binary-amd64_Packages'
removed '/var/lib/apt/lists/security.debian.org_debian-security_dists_bookworm-security_contrib_i18n_Translation-en'
removed '/var/lib/apt/lists/security.debian.org_debian-security_dists_bookworm-security_main_binary-amd64_Packages'
removed '/var/lib/apt/lists/security.debian.org_debian-security_dists_bookworm-security_main_i18n_Translation-en'

4. Removing OpenMediaVault cache packages...
removed '/var/cache/openmediavault/archives/Packages'

5. Creating new OpenMediaVault packages file...

6. Updating apt...
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:5 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:6 http://httpredir.debian.org/debian bookworm-backports InRelease [59.0 kB]
Get:7 http://security.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:8 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
Get:9 https://openmediavault.github.io/packages sandworm InRelease [12.8 kB]
Get:10 http://httpredir.debian.org/debian bookworm-backports/main amd64 Packages [253 kB]
Get:11 http://security.debian.org/debian-security bookworm-security/main amd64 Packages [190 kB]
Get:12 http://httpredir.debian.org/debian bookworm-backports/main Translation-en [212 kB]
Get:13 http://httpredir.debian.org/debian bookworm-backports/contrib amd64 Packages [5628 B]
Get:14 http://httpredir.debian.org/debian bookworm-backports/contrib Translation-en [5448 B]
Get:15 http://httpredir.debian.org/debian bookworm-backports/non-free amd64 Packages [11.1 kB]
Get:16 http://httpredir.debian.org/debian bookworm-backports/non-free Translation-en [7320 B]
Get:17 http://httpredir.debian.org/debian bookworm-backports/non-free-firmware amd64 Packages [3852 B]
Get:18 http://httpredir.debian.org/debian bookworm-backports/non-free-firmware Translation-en [2848 B]
Get:19 http://security.debian.org/debian-security bookworm-security/main Translation-en [116 kB]
Get:20 http://deb.debian.org/debian bookworm/main Sources [9487 kB]
Get:21 http://security.debian.org/debian-security bookworm-security/contrib amd64 Packages [644 B]
Get:22 http://security.debian.org/debian-security bookworm-security/contrib Translation-en [372 B]
Get:23 http://packages.openmediavault.org/public sandworm InRelease [12.8 kB]
Get:24 https://openmediavault.github.io/packages sandworm/main amd64 Packages [8398 B]
Get:25 http://packages.openmediavault.org/public sandworm/main amd64 Packages [8398 B]
Get:26 http://deb.debian.org/debian bookworm/main amd64 Packages [8787 kB]
Get:27 http://deb.debian.org/debian bookworm/main Translation-en [6109 kB]
Get:28 http://deb.debian.org/debian bookworm-updates/main Sources [1260 B]
Get:29 http://deb.debian.org/debian bookworm-updates/non-free Sources [1544 B]
Get:30 http://deb.debian.org/debian bookworm-updates/contrib Sources [776 B]
Get:31 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [2468 B]
Get:32 http://deb.debian.org/debian bookworm-updates/main Translation-en [2928 B]
Get:33 http://deb.debian.org/debian bookworm-updates/contrib amd64 Packages [768 B]
Get:34 http://deb.debian.org/debian bookworm-updates/contrib Translation-en [408 B]
Get:35 http://deb.debian.org/debian bookworm-updates/non-free amd64 Packages [12.8 kB]
Get:36 http://deb.debian.org/debian bookworm-updates/non-free Translation-en [7744 B]
Fetched 25.6 MB in 6s (4398 kB/s)
Reading package lists...

7. Saving current package list...

8. Updating plugin index...
Creating index of upgradeable packages ...
Creating index of plugins ...

</pre></code>
</details>

**Comment by ryecoaaron** [comment]
it doesn't look like it is adding the omvextras repo somehow.  What is the output of:
ls -al /etc/apt/sources.list.d/
cat /etc/apt/sources.list.d/omvextras.list

**Comment by chocmake** [comment]
```
total 24
drwxr-xr-x  2 root root 4096 Nov  2 18:35 .
drwxr-xr-x 14 root root 4096 Nov  2 18:35 ..
-rw-r--r--  1 root root  168 Nov  2 18:35 openmediavault-kernel-backports.list
-rw-r--r--  1 root root  409 Nov  2 18:35 openmediavault.list
-rw-r--r--  1 root root   60 Nov  2 18:35 openmediavault-local.list
-rw-r--r--  1 root root   87 Nov  2 18:35 openmediavault-os-security.list
```

and

`cat: /etc/apt/sources.list.d/omvextras.list: No such file or directory`

**Comment by ryecoaaron** [comment]
For some reason the omv-aptclean script is not detecting the "repos"  flag.  Can you confirm that you a typing exactly "repos"?

You could try this modified copy but that won't help determine the reason it isn't working on your system.
sudo wget -O - https://omv-extras.org/testing/omv-aptclean | sudo bash

**Comment by chocmake** [comment]
Yeah, confirmed the plural again with another test.

Tried the modified copy, too, though in the web UI the Borg plugin still unfortunately doesn't appear. Looking at the list it appears OMV Extras plugin is on v6.11 which I assume from other plugin versioning in the list should be v7x.

I have a few OMV Extra dependant plugins installed and configured but would uninstalling the v6.11 OMV Extras plugin and re-installing via the wiki's suggested `wget -O - https://github.com/OpenMediaVault-Plugin-Developers/packages/raw/master/install | bash` work?

Or would that bork the OMV Extra dependant plugins the moment I uninstall it initially?

**Comment by ryecoaaron** [comment]
omv-extras 6 is installed?? No wonder things arent working. yes, that script should fix it. I really dont know how you got in this state.

**Comment by chocmake** [comment]
OMV Extras v7 installed now, thanks.

When logged in via SSH as a non-privileged user and elevated to the root user via `su` I noticed a couple `dpkg` lines in the output saying it couldn't find certain paths in the PATH that were expected for root (despite being elevated to root). So I instead re-enabled password auth for SSH and logged in directly as root and it worked fine.

**Comment by ryecoaaron** [comment]
You need to use “su -“ to use root’s path.
