### ISSUE TITLE
Hey sorry I'm dumb and new

### ISSUE THREAD

**Issue by taojoannes420** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#32]
Hi, I'm new to this. 

I want to help enhance the functionality of this plugin but I'm not exactly sure how the code works. I could beat my head against it till I figured it out enough for a pull request, but if any of you have a few minutes to get together and walk me through the structure I'd be much obliged and would contribute some leet code. :D

**Comment by ryecoaaron** [comment]
Could this be done on the forum so others could benefit from the info? What functionality are you looking to add?

**Comment by taojoannes420** [comment]
See, told you I was dumb, didn't even know there was a forum. WIll look for
that.

Specifically and immediately, I'd like to be able to have control over the
scheduling and run some pre and post processing scripts. I want to be able
to shut down my docker containers so I'm backing up their configs cold,
then spin them back up again when it's finished.

Then I'd like to have some more borg functionality, like "borg info"
output, and some reporting would be nice, log integration at least.

I mean, to start. :D

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/

pre and post scripts probably wouldn't be hard to add.  It would be very similar to the rsnapshot code.

borg info would be easy to add.

reporting might be a challenge.

log integration - not sure what you mean but borg doesn't log syslog-like.  So, omv's log viewer isn't  the best for it.

**Comment by DistortedBit** [comment]
Any update regarding the pre and post scripts? I'm in the same boat, I want to gracefully shutdown all my docker containers and then run backup and spin them back up.


This is essentially a must when backing up containers that has databases in it to ensure consistency.


It's there's anyone working on this, I'd be happy to collaborate to get it out soon.

**Comment by ryecoaaron** [comment]
No, I forgot about it.  I will look at it.  There is pretty much no one other than me working on omv-extras plugins.

**Comment by DistortedBit** [comment]
Oh man I appreciate your work. If you are open to a small donation please show me the way.


I'm lacking some basics how the whole thing works and integrates with omv. 
If there's a guide to setup the development environment I might be able to help you here and there.

**Comment by ryecoaaron** [comment]
If you would like to test my changes, that would be very helpful.

wget https://omv-extras.org/testing/openmediavault-borgbackup_6.2_all.deb
sudo dpkg -i openmediavault-borgbackup_6.2_all.deb

If you send me a private message on the forum, we can discuss how to setup a dev environment.

**Comment by DistortedBit** [comment]
Thank you for the prompt update. The pre and post scripts work well.

I'm having issues with paaaphrases though. It seems they are not escaped at all during the create repository section and will fail borg paaaphrase env not set.

**Comment by ryecoaaron** [comment]
That must be from my previous change. I will look at that tomorrow. Thanks for testing.

**Comment by DistortedBit** [comment]
I have found the root cause of the password problem. I have created an issue with reproduction steps. Hope that helps.
