### ISSUE TITLE
Depreciated parameter still in use

### ISSUE THREAD

**Issue by Struppie** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#35]
Hi,
with the newest version of OMV (6.0.41.1) and the borgbackup plugin I'm getting this warning:
>>
Warning: "--prefix" has been deprecated. Use "--glob-archives 'yourprefix*'" (-a) instead.
<<

I assume, this is a result of using this parameter in the UI of the borgbackup plugin:
<img width="626" alt="image" src="https://user-images.githubusercontent.com/58170922/192510647-a607cd0d-38e4-4e04-8beb-fcc1c80cfd2c.png">

Would be nice, if the parameter usage can be adapted to use the current ones and avoid depreciated ones.
Many thanks! :)

**Comment by Struppie** [comment]
many thanks for this very quick response! Of course this is only a minor issue, just wanted to mention it. Thanks for taking care! :)

**Comment by ryecoaaron** [comment]
6.3 is in the repo now with this change.
