### ISSUE TITLE
Use SSH keys that OMV knows about

### ISSUE THREAD

**Issue by dmtucker** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#36]
From #19:
> The plugin would only use Certs from Certificates > SSH if there was a dropdown to select one. The borgbackup command doesn't have a way to specify a cert that I know. So, I can't add this.

I believe this can be done with `BORG_RSH` or `--rsh`:
>           BORG_RSH
>                     When set, use this command instead of ssh. This can be used to specify ssh options, such as a custom identity
>                     file ssh -i /path/to/private/key. See man ssh for other options. Using the --rsh CMD commandline option over‐
>                     rides the environment variable.

**Comment by ryecoaaron** [comment]
Is this you?  https://forum.openmediavault.org/index.php?thread/44763-borgbackup-plugin-how-to-specify-borg-rsh/

**Comment by dmtucker** [comment]
Nope! Hadn't found that thread yet :sweat_smile:

**Comment by ryecoaaron** [comment]
6.3 is in the repo now.  Add any environment variables you need to /etc/default/openmediavault-borgbackup.
