### ISSUE TITLE
Support BORG_REMOTE_PATH or --remote-path

### ISSUE THREAD

**Issue by dmtucker** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#37]
Hey there :wave: I've been using this plugin more and more lately. Thanks for the super useful integration!

I am currently working on moving away from `rsync` in favor of a remote borg repo with rsync.net.
It works fine, but rsync.net has a really old version of `borg` by default. Because of that I get a bunch of noise in my runs:
```
Mon 03 Oct 2022 03:45:12 AM PDT Starting backup

Remote: Borg 0.29.0: exception in RPC call:
Remote: Traceback (most recent call last):
Remote:   File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 96, in serve
Remote: TypeError: open() takes from 2 to 5 positional arguments but 7 were given
Remote: Command 'uname -p 2> /dev/null' is not in the allowed list.
Remote: Platform: FreeBSD usw-s008.rsync.net 12.2-RELEASE FreeBSD 12.2-RELEASE rsync_12_2 amd64
Remote: Python: CPython 3.4.3
Remote:
Please note:
If you see a TypeError complaining about the number of positional arguments
given to open(), you can ignore it if it comes from a borg version < 1.0.7.
This TypeError is a cosmetic side effect of the compatibility code borg
clients >= 1.0.7 have to support older borg servers.
This problem will go away as soon as the server has been upgraded to 1.0.7+.
Creating archive at  ...
```
And it shows again for `prune`...

Apparently they have a newer version called `borg1`, but I don't see a good way to get the plugin to use that instead.
It would require passing `--remote-path borg1` or setting `BORG_REMOTE_PATH`:
> BORG_REMOTE_PATH
>                     When  set,  use  the  given path as borg executable on the remote (defaults to "borg" if unset).  Using --re‐
>                     mote-path PATH commandline option overrides the environment variable.

Any chance we could get support for this added? TIA

**Comment by dmtucker** [comment]
https://forum.openmediavault.org/index.php?thread/44763-borgbackup-plugin-how-to-specify-borg-rsh/&postID=325573#post325573

> I'm looking into a way to allow you to add any borg environment variables by just adding them to /etc/default/openmediavault-borgbackup. It will just require a chance to core OMV which I am going to submit a pull request for. Then I can make a change to the plugin. It will take some time since Volker is on vacation.

:sunglasses:

**Comment by ryecoaaron** [comment]
6.3 is in the repo now.  Add any environment variables you need to /etc/default/openmediavault-borgbackup.

**Comment by dmtucker** [comment]
Is there a way to only apply variables in `/etc/default/openmediavault-borgbackup` to particular Archives?

**Comment by ryecoaaron** [comment]
No. No one mentioned that they might need different variables per repo or archive. It was a challenge getting the scheduled tasks and web interface to use the same variables. It will be even more challenging to get specific variables. I will probably have to add a tab to the plugin to manage them. Yuck.

**Comment by dmtucker** [comment]
:ok_hand: No worries! That'd be nice, but this works great for me as is... I only have 1 remote repo ATM and Borg seems to ignore `BORG_REMOTE_PATH` and `BORG_RSH` for local backups. Thanks for the quick turnaround!

**Comment by ryecoaaron** [comment]
6.4 is in the repo.  All actions except creation of a repo will use the environment variables in the Environment Variables tab.  Because a variable can't be created until a repo exists, creation of a repo will require the variables be placed in /etc/default/openmediavault-borgbackup

**Comment by dmtucker** [comment]
Cool! Thank you :+1:
