### ISSUE TITLE
How to install openmediavault-borgbackup plugin

### ISSUE THREAD

**Issue by zandet97** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#39]
Hello everyone !
I would like to install the omv plugin so that it is accessible from the Workbench but I don't understand how to proceed. I couldn't find any documentation that details the installation of the borgbackup plugin for the Workbench. I only found the official borgbackup ([https://docs.openmediavault.org/en/latest/installation/index.html](url)) documentation, which details the installation for a borgbackup installation (on a debian system for example) but not for the Workbench. I specify that I am new to omv and linux systems. Sorry for my English ! Thank you beforehand.

**My System :** 
Debian 11, bullseye
Linux openmediavault 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+1 (2022-03-08) x86_64 GNU/Linux
**openmedivault information :**
Release : 6.0.24-1
Codename : Shaitan

**Comment by ryecoaaron** [comment]
You need to install omv-extras and then you can install the plugin from the Plugins tab. Pleasee read https://wiki.omv-extras.org/doku.php?id=omv6:new_user_guide

**Comment by zandet97** [comment]
Thanks a lot!
