### ISSUE TITLE
Add an option to compact

### ISSUE THREAD

**Issue by Tontonjo** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#42]
Hey! 

As far as i know OMV plugin has no option in order to trigger a repository compaction.

This is needed to be ran sometimes in order to free up space as per documentation says:
https://borgbackup.readthedocs.io/en/stable/usage/compact.html

On my system, the compaction freed about 4 TO (compaction was not run since at least june 2023
![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/assets/60965766/e193d8b9-3b14-4ee7-9e3f-c9a1cff95c86)

I thing it may be a usefull if not necessary option to add (appart if it's already implemented :) )

Regards

Tonton Jo

**Comment by ryecoaaron** [comment]
Added.  Will be in next release.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/492bddf6d710b89cb28377f9030d24acba899b35

**Comment by Tontonjo** [comment]
> Added. Will be in next release. [492bddf](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/commit/492bddf6d710b89cb28377f9030d24acba899b35)

That was blazing fast!

Thanks a lot for your work.
