### ISSUE TITLE
Post-script isn't executed when running job manually, only on sheduled runs

### ISSUE THREAD

**Issue by netw0rk-noob** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#47]
When I tried debugging my post-script I noticed, that it is only ever executed when the archive is run via cron, not if it is run via "Run" from the "archives" tab of the WebUI. In contrast the pre-script is run in both cases.

Is that a bug or a feature I'm not getting the sense of?

**Comment by ryecoaaron** [comment]
It should run the scripts unless they are not executable.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/blob/master/usr/share/openmediavault/engined/rpc/borgbackup.inc#L716

**Comment by ryecoaaron** [comment]
as root:

sudo monit stop omv-engined
sudo omv-engined -df

then run the scheduled job.  You might see output.

**Comment by ryecoaaron** [comment]
sudo monit stop omv-engined
sudo killall omv-engined
sudo omv-engined -df

**Comment by ryecoaaron** [comment]
> Hence I'm pretty sure that the post-script command line doesn't get executed at manual runs at all and it isn't a problem with my script.

I linked to the code that runs the script earlier in this thread. And it is run on my systems. I’m at a VMware conference for the next few days and won’t be able to look at this in more depth. php running out of memory could very well be the problem.
