### ISSUE TITLE
Make port configurable

### ISSUE THREAD

**Issue by ShadowBr0ther** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#48]
Hello. 
I want to use this integration for pushing backups to Hetzner Storage Cloud. 
Their ssh connection wourks through port 23 though. Would it be possible to integrate a way to make the port configurable?

Greetings!

**Comment by ryecoaaron** [comment]
You can do this by setting the BORG_RSH environment variable for "repo creation" and the repo after creation by customizing the ssh command with something like "ssh -p <alternate-port>"

**Comment by ShadowBr0ther** [comment]
Perfect that worked. Thank you!
