### ISSUE TITLE
Compression Type set to 'None' applying compression

### ISSUE THREAD

**Issue by chocmake** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#49]
With a test directory of 11k files @ ~13GB I noticed that when the archive item was left at the default *Compression Type* of 'None' Borg was still applying compression.

Archive result when set to 'None':
Original size: `13.24 GB` / Compressed size: `12.51 GB` / Deduplicated size: `10.43 GB`

According to the log (via *Archives>Info* button in the GUI) it appears the compression argument the plugin passes to Borg is `--compression auto,none,9`.

Based on the Borg [docs](https://borgbackup.readthedocs.io/en/stable/usage/create.html#examples) examples it seems this syntax means 'only compress compressible data with the 2nd value's compression type using the 3rd value's compression factor. However despite the second arg being `none` it appears to still apply compression (potentially upstream bug?).

Per those same examples though if wanting to ordinarily use compression `none` the suggested syntax appears to be `--compression none` (single value argument).

---

I tested setting the archive to LZ4 compression (according to the docs the default) as a separate test to see if Borg was applying that and the logged output showed identical compression. Which makes me think perhaps Borg is falling back to default compression when it encounters a second argument of `none` when it expects a single value argument instead.

**Comment by ryecoaaron** [comment]
I will release an update later.

**Comment by chocmake** [comment]
Tested v7.0.9, which I updated via *System>Update Management>Updates* in the web UI.

Oddly it appears to still be using the existing `--compression auto,none,9` argument and applying compression when *Compression Type* left at the default 'None'.

Tried this on both the existing test archive I'd made, then deleted that one and created a new one in case it only applied to new archives but the same result.

Command shown via the web UI when running:

`Command: export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; export BORG_PASSPHRASE=''; /usr/bin/borg create --list --stats --verbose --compression auto,none,9 "<path to repo>::borg-archive-test-2-{now:%Y-%m-%d_%H-%M-%S}" '<path to source>' --exclude '' 2>&1`

And the logged info shows the same original/compressed/deduplicated sizes.

**Comment by ryecoaaron** [comment]
Huh, it was working on my systems.  What is the output of:
sudo omv-showkey borgbackup  # might have to remove hostnames/passwords
sudo omv-salt deploy run borgbackup

**Comment by chocmake** [comment]
> `sudo omv-showkey borgbackup` output:

```
<borgbackup>
  <repos>
    <repo>
      <uuid>a3621d24-5af5-4e0c-b48f-88a610e07745</uuid>
      <name>Borg-Repo-Test</name>
      <type>local</type>
      <sharedfolderref>[snip]</sharedfolderref                                                                                 >
      <uri></uri>
      <passphrase></passphrase>
      <encryption>0</encryption>
    </repo>
  </repos>
  <archives>
    <archive>
      <enable>1</enable>
      <uuid>30b1046a-f3e0-437f-b6db-c7026f2db155</uuid>
      <name>borg-archive-test-2</name>
      <reporef>a3621d24-5af5-4e0c-b48f-88a610e07745</reporef>
      <compressiontype>none</compressiontype>
      <compressionratio>9</compressionratio>
      <onefs>0</onefs>
      <noatime>0</noatime>
      <include>/srv/dev-disk-by-uuid-[snip]/Test</include>
      <exclude></exclude>
      <hourly>0</hourly>
      <daily>7</daily>
      <weekly>4</weekly>
      <monthly>3</monthly>
      <yearly>0</yearly>
      <ratelimit>0</ratelimit>
      <list>1</list>
      <email>0</email>
      <prescript></prescript>
      <postscript></postscript>
      <basedir></basedir>
    </archive>
  </archives>
  <envvars></envvars>
</borgbackup>
```

> `sudo omv-salt deploy run borgbackup` output:

<details><code><pre>
debian:
----------
          ID: configure_borg_envvar_dir
    Function: file.directory
        Name: /etc/borgbackup
      Result: True
     Comment: The directory /etc/borgbackup is in the correct state
     Started: 18:22:17.877291
    Duration: 4.393 ms
     Changes:
----------
          ID: remove_envvar_files
    Function: module.run
      Result: True
     Comment: file.find: ['/etc/borgbackup/borg-envvar-a3621d24-5af5-4e0c-b48f-88a610e07745', '/etc/borgbackup/borg-envvar-creation']
     Started: 18:22:17.882151
    Duration: 4.023 ms
     Changes:
              ----------
              file.find:
                  - /etc/borgbackup/borg-envvar-a3621d24-5af5-4e0c-b48f-88a610e07745
                  - /etc/borgbackup/borg-envvar-creation
----------
          ID: configure_borg_envvar_a3621d24-5af5-4e0c-b48f-88a610e07745
    Function: file.managed
        Name: /etc/borgbackup/borg-envvar-a3621d24-5af5-4e0c-b48f-88a610e07745
      Result: True
     Comment: File /etc/borgbackup/borg-envvar-a3621d24-5af5-4e0c-b48f-88a610e07745 updated
     Started: 18:22:17.886297
    Duration: 101.856 ms
     Changes:
              ----------
              diff:
                  New file
----------
          ID: configure_borg_envvar_creation
    Function: file.managed
        Name: /etc/borgbackup/borg-envvar-creation
      Result: True
     Comment: File /etc/borgbackup/borg-envvar-creation updated
     Started: 18:22:17.988274
    Duration: 55.584 ms
     Changes:
              ----------
              diff:
                  New file
----------
          ID: configure_borg_hourly_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/hourly.d
      Result: True
     Comment: The directory /var/lib/openmediavault/borgbackup/hourly.d is in the correct state
     Started: 18:22:18.043955
    Duration: 3.116 ms
     Changes:
----------
          ID: configure_borg_daily_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/daily.d
      Result: True
     Comment: Files cleaned from directory /var/lib/openmediavault/borgbackup/daily.d
     Started: 18:22:18.047178
    Duration: 2.059 ms
     Changes:
              ----------
              /var/lib/openmediavault/borgbackup/daily.d/borgbackup-30b1046a-f3e0-437f-b6db-c7026f2db155:
                  ----------
                  removed:
                      Removed due to clean
              removed:
                  - /var/lib/openmediavault/borgbackup/daily.d/borgbackup-30b1046a-f3e0-437f-b6db-c7026f2db155
----------
          ID: configure_borg_weekly_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/weekly.d
      Result: True
     Comment: The directory /var/lib/openmediavault/borgbackup/weekly.d is in the correct state
     Started: 18:22:18.049325
    Duration: 1.682 ms
     Changes:
----------
          ID: configure_borg_monthly_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/monthly.d
      Result: True
     Comment: The directory /var/lib/openmediavault/borgbackup/monthly.d is in the correct state
     Started: 18:22:18.051130
    Duration: 1.534 ms
     Changes:
----------
          ID: configure_borg_yearly_dir
    Function: file.directory
        Name: /var/lib/openmediavault/borgbackup/yearly.d
      Result: True
     Comment: The directory /var/lib/openmediavault/borgbackup/yearly.d is in the correct state
     Started: 18:22:18.052752
    Duration: 1.694 ms
     Changes:
----------
          ID: configure_borg_crond
    Function: file.managed
        Name: /etc/cron.d/openmediavault-borgbackup
      Result: True
     Comment: File /etc/cron.d/openmediavault-borgbackup is in the correct state
     Started: 18:22:18.054527
    Duration: 101.54 ms
     Changes:
----------
          ID: configure_borg_borg-archive-test-2_cron_file
    Function: file.managed
        Name: /var/lib/openmediavault/borgbackup/daily.d/borgbackup-30b1046a-f3e0-437f-b6db-c7026f2db155
      Result: True
     Comment: File /var/lib/openmediavault/borgbackup/daily.d/borgbackup-30b1046a-f3e0-437f-b6db-c7026f2db155 updated
     Started: 18:22:18.156169
    Duration: 1.825 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0750

Summary for debian
-------------
Succeeded: 11 (changed=5)
Failed:     0
-------------
Total states run:     11
Total run time:  279.306 ms
</pre></code></details>

**Comment by ryecoaaron** [comment]
What is the output of:

 cat /var/lib/openmediavault/borgbackup/daily.d/borgbackup-30b1046a-f3e0-437f-b6db-c7026f2db155

**Comment by chocmake** [comment]
```
#!/bin/sh

# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

extra="/etc/borgbackup/borg-envvar-a3621d24-5af5-4e0c-b48f-88a610e07745"
if [ -f "${extra}" ]; then
  set -a
  . ${extra}
  set +a
fi

# Setting this, so the repo does not need to be given on the commandline:
export BORG_REPO='/srv/dev-disk-by-uuid-4d4fabbb-9793-4d1a-9cf1-29313ec47825/Bor                                                             g-Repo-Test/'

# Setting this, so you won't be asked for your repository passphrase:
export BORG_PASSPHRASE=''

# some helpers and error handling:
info() { printf "\n%s %s\n\n" "$( date )" "$*"; }
trap 'echo $( date ) Backup interrupted >&2; exit 2' INT TERM

info "Starting backup" >> /var/log/borgbackup.log 2>&1

borg create \
  --verbose \
  --filter AME \
  --list \
  --stats \
  --show-rc \
  --compression none \
  --exclude-caches \
  ::"borg-archive-test-2-{now:%Y-%m-%d_%H-%M-%S}" \
  '/srv/dev-disk-by-uuid-[snip]/Test' \
  >> /var/log/borgbackup.log 2>&1

backup_exit=$?

info "Pruning repository" >> /var/log/borgbackup.log 2>&1

borg prune \
  --list \
  --glob-archives 'borg-archive-test-2-*' \
  --show-rc \
  --keep-daily 7 \
  --keep-weekly 4 \
  --keep-monthly 3 \
  >> /var/log/borgbackup.log 2>&1

prune_exit=$?

# use highest exit code as global exit code
global_exit=$(( backup_exit > prune_exit ? backup_exit : prune_exit ))

if [ ${global_exit} -eq 1 ]; then
  info "Backup and/or Prune finished with a warning"
fi

if [ ${global_exit} -gt 1 ]; then
  info "Backup and/or Prune finished with an error"
fi

exit ${global_exit}
```

(The source dir path has been manually truncated here with with `[snip]`)

**Comment by ryecoaaron** [comment]
--compression none \

The compress line is correct.  Are you still seeing the issue?

**Comment by chocmake** [comment]
> The compress line is correct. Are you still seeing the issue?

Yeah. When *Run* button is used from the GUI it continues to show the old argument (like [this](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/issues/49#issuecomment-2463673131) post). With the *Info* button log showing the same thing.

If the commands from that `daily.d` script is what is meant to be triggering it's weird. I checked the contents of `/var/lib/openmediavault/borgbackup/` to see if there happened to be any other scripts but only `daily.d` contains anything (that script above).

**Comment by ryecoaaron** [comment]
I forgot about the manual run. I rarely use that button. It is an easy fix that I will fix tomorrow.

**Comment by ryecoaaron** [comment]
7.0.10 in the repo.

**Comment by chocmake** [comment]
Thanks! Just tested with a fresh archive and no compression is applied when triggered via the GUI.
