### ISSUE TITLE
Update plugin to borg 1.1.10

### ISSUE THREAD

**Issue by adatum** [OpenMediaVault-Plugin-Developers/openmediavault-borgbackup#5]
Hello, the borg version from this plugin is currently at 1.1.5. That is more than a year old, and there have been several releases since then with bug fixes and improvements. 

Would it be possible to update the plugin to borg 1.1.10 which is the current version?

**Comment by ryecoaaron** [comment]
While 1.1.5 is in the repo from a long time ago, 1.1.9 is in the stretch-backports repo (enabled by default).  The idea is to use the version in the Debian repos.

**Comment by adatum** [comment]
Is the suggestion to use `apt install borgbackup` instead of the OMV plugin?

**Comment by ryecoaaron** [comment]
No.  The plugin installs the borgbackup package because it is a dependency of the plugin.  The plugin is just a frontend for borgbackup.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-borgbackup/blob/master/debian/control#L12

**Comment by adatum** [comment]
Ok, but I'm afraid I don't understand your point. Why is OMV using an older version if stretch-backports has a more recent version? And what do you suggest users do?

Btw, I installed the the OMV plugin for borg only for ease of maintenance. I don't actually use the OMV gui frontend.

**Comment by ryecoaaron** [comment]
I guess I never noticed but borgbackup isn't pinned to use it from backports.  Why do you need a newer version?  The plugin is tested on the version that gets installed by default.  If you want the newer version, just apt-get install -t stretch-backports borgbackup

Ease of maintenance?  Not sure what you mean by that.

**Comment by adatum** [comment]
Wouldn't it be better to have the plugin to install from backports instead of manual user intervention?

> Ease of maintenance?

Plugins automatically update, yes?

**Comment by ryecoaaron** [comment]
Yes.  As I said, I didn't realize I never pinned it to come from backports.  BUT I had to build a version to put in the omv-extras repo in case someone has backports disabled.  Maybe I will add the pinning but I see this as low priority unless someone gives me a good reason a new version is needed.

No.  They update the exact same way as packages do in the Updates tab -or- apt-get upgrade.

**Comment by adatum** [comment]
> Maybe I will add the pinning but I see this as low priority unless someone gives me a good reason a new version is needed.

The [changelog](https://borgbackup.readthedocs.io/en/stable/changes.html#changelog) shows many bugfixes (including a security fix), new features (which clients with an updated version might expect), and occasional performance improvements. On backup software I especially want all the bugfixes I can get. 

> No. They update the exact same way as packages do in the Updates tab -or- apt-get upgrade.

I got that impression since I didn't see any Update button on the OMV Plugins page and the [documentation](https://openmediavault.readthedocs.io/en/latest/plugins.html#benefits) mentions:

> Automatic updates - ensure Stability & Security.

**Comment by ryecoaaron** [comment]
Unfortunately, that argument means I should be building a new package for the omv-extras repo as well.  Yuck.  I will work on it.

Plugins are normal Debian (.deb) packages starting with openmediavault-.  So, the updates tab performs all updates.  I have no idea why the documentation says anything automatically updates.  apt-get update is run daily by a cronjob but nothing to run apt-get upgrade.

**Comment by ryecoaaron** [comment]
omv-extras 5.0.6 is in the repo and it adds the borg pinning.

**Comment by adatum** [comment]
@ryecoaaron Appreciated! Will the update be made for OMV 4.x too? I'll be staying on the stable release for a while.

**Comment by ryecoaaron** [comment]
I wasn't planning on it but 4.1.16 is in the repo.

**Comment by adatum** [comment]
Awesome. Thank you so much!!

Upgraded. Tonight's backups will enjoy borg 1.1.9
